apiVersion: apps/v1
kind: Deployment 
metadata:
  name: conda-debug
  labels:
    app: conda-debug
spec:
  selector:
    matchLabels:
      app: conda-debug
  template:
    metadata:
      labels:
        app: conda-debug
    spec:
      containers:
      - name: conda-debug
        command: ["tail", "-f", "/dev/null"]
        image: continuumio/miniconda3:latest 
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: target
          mountPath: /environments
      volumes:
      - name: target
        persistentVolumeClaim:
          claimName: nebari-conda-store-storage  
